name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies + run checks
        run: |
          corepack enable
          pnpm install
          pnpm lint
          pnpm check
          pnpm build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: sveltekit-build
          path: .svelte-kit/cloudflare

  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies + run checks
        run: |
          corepack enable
          pnpm install
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: sveltekit-build
          path: .svelte-kit/cloudflare

      - name: Deploy Preview to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .svelte-kit/cloudflare --project-name=sveltekit --branch=${{ github.head_ref }}

  changesets:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies + run checks
        run: |
          corepack enable
          pnpm install

      - name: Run Changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
