name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure changeset exists
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          VALID_CHANGESET=$(echo "$CHANGED_FILES" | grep '^\.changeset/.*\.md$' | grep -v '^\.changeset/README\.md$')

          if [ -z "$VALID_CHANGESET" ]; then
            echo "⚠️  You must add a changeset in .changesets/ (excluding README.md)!"
            exit 1
          fi
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies + run checks
        run: |
          corepack enable
          pnpm install
          pnpm lint
          pnpm check

  build:
    runs-on: ubuntu-latest
    needs:
      - prerequisites
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies + run checks
        run: |
          corepack enable
          pnpm install
          pnpm build
          rm .svelte-kit/cloudflare/_worker.js.map

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: sveltekit-build
          path: .svelte-kit/cloudflare

  deploy-preview:
    needs:
      - prerequisites
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies + run checks
        run: |
          corepack enable
          pnpm install

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: sveltekit-build
          path: .svelte-kit/cloudflare

      - name: Deploy Preview to Cloudflare Pages
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '4.34.0'
          command: pages deploy .svelte-kit/cloudflare --project-name=sveltekit --branch=${{ github.head_ref }}
          packageManager: pnpm

      - name: Comment Preview URL on PR
        uses: moojing/cf-preview-bot@v1
        with:
          deployment_url: ${{ steps.deploy.outputs.deployment-url }}
          branch_preview_url: ${{ steps.deploy.outputs.pages-deployment-alias-url }}
