name: Pull Request
on:
  push:
    branches:
      - main

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies + run pre-release checks
        run: |
          corepack enable
          pnpm --version

          pnpm install
          pnpm lint
          pnpm check
          pnpm build

        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}

      - name: Upload build output
        if: github.actor == 'version-app[bot]'
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path:
            - .sveltekit

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}
